services:
  app:
    image: movies_api:latest
    depends_on:
      - mongoDb
    ports:
      - "8080:8080"
    environment:
      - MONGO_HOST=mongodb
      - SEED_ENABLED=true
  mongoDb:
    image: mongo
    ports:
      - "27017:27017"
    expose:
      - 27017