services:
  app:
    image: movies_api:latest
    depends_on:
      mongoDb:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      - MONGO_HOST=mongodb
      - SEED_ENABLED=true
  mongoDb:
    image: mongo
    ports:
      - "27017:27017"
    expose:
      - 27017
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5